### ISSUE TITLE
503 Database version is behind, please apply migration -> [Nothing to migrate]

### ISSUE THREAD

**Issue by aaronnewsome** [LycheeOrg/Lychee#1082]
Yesterday I tried logging into Lychee and I get this message that the database version is behind. The message says:

503 Database version is behind, please apply migration

I put in the admin username and password, click migrate and then I get a plain white page saying nothing to migrate. When I click the button to apply the migration, nothing at all gets logged to the console.

I've been using Lychee for over 4 months, mostly without issue. This problem seems to have come out of nowhere. I am using the docker image and I previously used the dev tagged image version. This was recommended here on this forum to fix an issue I was having with the 4.3.0 release. The dev tagged image did fix this issue I was having and it's been working just fine for the last few months. I have around 20,000 photos in Lychee.

I backup the postgres database nightly and backup the raw image file directories weekly. In order to try and resolve this issue, I restored a database backup from a few days ago and tried starting lycheeorg/lychee:dev again but got the same issue.

So I restored the database again and tried earlier versions. No matter what version of lychee I've tried, I get the same result. I've looked at the data in my database, seems ok to me. I've looked at the migrations table from my regular database and the restored database. Not sure what I'm looking for but they both seem ok to me,

As I write this post, I restored the database from 2021-08-07 once again and then freshly booted the lychee:dev. The console startup ouput does not show anything that helps me figure out what the heck is going on or why lychee has broken so badly all of a sudden.

Here's the result of the console log during container startup:

```
Lychee Version: 4.3.2 (dev)
Lychee Commit:  3a0798c
https://github.com/LycheeOrg/Lychee/commit/3a0798c62818f87531c4c9505bb6ef292f09227b
-------------------------------------
**** Make sure the /conf and /uploads folders exist ****
**** Create the symbolic link for the /uploads folder ****
**** Create the symbolic link for the /sym folder ****
**** Create the symbolic link to the old Lychee-Laravel folder ****
**** Copy the .env to /conf ****
**** Inject .env values ****
**** Generate the key (to make sure that cookies cannot be decrypted etc) ****

**************************************
*     Application In Production!     *
**************************************

Command Canceled!
**** Migrate the database ****

Nothing to migrate.
**** Check user.css exists and symlink it ****
**** Create user and use PUID/PGID ****
 	User UID :	1026
 	User GID :	100
**** Set Permissions ****
**** Setup complete, starting the server. ****
```

It looks like the dev tag has been overwritten with a new version of Lychee a few days ago. I think this is what caused my problem. However,  I don't have any way to see which version of my database backup belongs to which version of Lychee. Is there anyway to look at the database to figure out which exact version of Lychee is supposed to work with that version of the database? I can either fix whatever is causing this database issue or restore the DB and revert to an earlier version if I can figure out which tag I should be using.

**Comment by aaronnewsome** [comment]
I saw in a similar issue with database that the poster ran the SQL to get the Lychee version from the DB:

```

lychee434=# select key, value from configs where key = 'version';
   key   | value  
---------+--------
 version | 04030

```

So it looks like my database backup was created with 4.3.0? Am I reading that correctly? Going to try and find this version in the docker repository and see if I have any better luck with this one.

Also, can I mention that testing these takes HOURS just to see if they work. The "set permissions" stage of the docker container boot literally takes about 2 hours. Not sure why it needs to be constantly setting permissions on every boot. I'm considering modifying the docker image and removing this time consuming step, or running the lychee photo storage on SSD or both. Either way, a boot time of more than an hour is not good.

**Comment by aaronnewsome** [comment]
Continue to follow some troubleshooting advice from the other thread, I ran "php artisan db". Here's the result:


```
root@lychee-df964cb96-bc2qh:/var/www/html/Lychee# php artisan db
sh: 1: exec: psql: not found

In Process.php line 267:
                                            
  The command "'psql' 'lychee434'" failed.  
                                            
  Exit Code: 127(Command not found)         
                                            
  Working directory: /var/www/html/Lychee   
                                            
  Output:                                   
  ================                          
                                            
                                            
  Error Output:                             
  ================                          
                  
```

I'm not sure how this is possible. How is the psql command not found? I've been running Lychee for nearly 5 months.

**Comment by d7415** [comment]
Ok, so something weird is going on here...

- The image reports `Lychee Version: 4.3.2 (dev)` which puts it before 5th June.
- The database reports 4.3.0, which the migration in 4.3.2 (or 4.3.1) should have fixed.

As for the permissions, that's to stop stupid errors if they're wrong. We could potentially add a switch to that.

As for `psql`, the docker image tries to be minimal while supporting lychee's features. `apt update && apt install postgresql-client-11` (adjust for your postgresql version) should install the client tools.

**Comment by kamil4** [comment]
What is the output of `php artisan migrate:status`?

My guess is that the database migration is somehow failing for your instance. You can try running `php artisan migrate` in the console to see what it does but based on similar past issues, that's unlikely to provide meaningful diagnostics if the migration had already been run (and failed). So to do it _properly_, you should restore the database and then run `php artisan migrate` from the console (without running it via the GUI). Hopefully that will give us the info we need to figure out what might be going wrong.

I can't really help you with the boot time, other than asking: do you actually need to reboot? You should be able to simply restore the database on a booted image, no?

**Comment by d7415** [comment]
> run `php artisan migrate` from the console (without running it via the GUI)

It's actually harder *not* to do this in the Docker image, as it does it on boot.

**Comment by d7415** [comment]
Looks like that image was from a little before v4.3.4. (the commit hash and github link are in the startup output).

**Comment by aaronnewsome** [comment]
> I can't really help you with the boot time, other than asking: do you actually need to reboot? You should be able to simply restore the database on a booted image, no?

The docker image is running in Kubernetes, so in order to apply a new version the container needs to be destroyed and rebuilt. Obviously the photo storage and and DB are on persistent storage.

**Comment by aaronnewsome** [comment]
Ok, I ran the migrate status command. Here's the output.

```
root@lychee-df964cb96-bc2qh:/var/www/html/Lychee# php artisan migrate:status

+------+-------------------------------------------------------------+-------+
| Ran? | Migration                                                   | Batch |
+------+-------------------------------------------------------------+-------+
| Yes  | 2014_10_12_000000_create_users_table                        | 1     |
| Yes  | 2018_08_03_110935_create_albums_table                       | 1     |
| Yes  | 2018_08_03_110936_create_photos_table                       | 1     |
| Yes  | 2018_08_03_110942_create_configs_table                      | 1     |
| Yes  | 2018_08_03_111324_create_logs_table                         | 1     |
| Yes  | 2018_08_10_134924_move_settings                             | 1     |
| Yes  | 2018_08_15_102039_move_albums                               | 1     |
| Yes  | 2018_08_15_103716_move_photos                               | 1     |
| Yes  | 2018_10_30_135411_sharing                                   | 1     |
| Yes  | 2019_02_21_114356_create_pages_table                        | 1     |
| Yes  | 2019_02_21_114408_create_page_contents_table                | 1     |
| Yes  | 2019_06_21_180451_create_sym_links_table                    | 1     |
| Yes  | 2019_09_28_171753_config_fix                                | 1     |
| Yes  | 2019_09_28_190822_photos_fix                                | 1     |
| Yes  | 2019_10_01_add_livephoto_cols                               | 1     |
| Yes  | 2019_10_02_1400_config_map_display_public                   | 1     |
| Yes  | 2019_10_03_214750_frame_refresh_in_sec                      | 1     |
| Yes  | 2019_10_06_1400_config_map_providers                        | 1     |
| Yes  | 2019_10_06_152017_add_force_32bit_ids                       | 1     |
| Yes  | 2019_10_07_0900_config_map_include_sub_albums               | 1     |
| Yes  | 2019_10_09_233402_config_map_mod                            | 1     |
| Yes  | 2019_10_11_093442_config_check_update_every                 | 1     |
| Yes  | 2019_12_02_2100_config_exiftool                             | 1     |
| Yes  | 2019_12_15_0700_add_share_button_visible_option             | 1     |
| Yes  | 2019_12_15_1000_config_check_update_every_cat_fix           | 1     |
| Yes  | 2019_12_25_0600_config_exiftool_ternary                     | 1     |
| Yes  | 2020_01_018_2300_config_import_via_symlink                  | 1     |
| Yes  | 2020_01_04_1200_config_has_ffmpeg                           | 1     |
| Yes  | 2020_01_26_1200_config_public_sorting                       | 1     |
| Yes  | 2020_01_28_133201_composer_update                           | 1     |
| Yes  | 2020_02_14_0600_location_decoding                           | 1     |
| Yes  | 2020_03_11_124417_increase_length_photo_type                | 1     |
| Yes  | 2020_03_17_200000_unhide_configs                            | 1     |
| Yes  | 2020_04_19_122905_bump_version                              | 1     |
| Yes  | 2020_04_22_155712_bump_version040002                        | 1     |
| Yes  | 2020_04_29_000250_bump_version040003                        | 1     |
| Yes  | 2020_05_12_114228_rss                                       | 1     |
| Yes  | 2020_05_12_161427_bump_version040005                        | 1     |
| Yes  | 2020_05_19_174233_config_prefer_available_xmp_metadata      | 1     |
| Yes  | 2020_05_26_135052_bump_version040006                        | 1     |
| Yes  | 2020_06_04_104605_config_editor_enabled                     | 1     |
| Yes  | 2020_07_11_104605_config_lossless_optimization              | 1     |
| Yes  | 2020_07_11_184605_update_licences                           | 1     |
| Yes  | 2020_07_26_085322_config_swipe_tolerance                    | 1     |
| Yes  | 2020_07_29_132731_config_local_takestamp                    | 1     |
| Yes  | 2020_08_21_123622_add_smart_tag_album_cols                  | 1     |
| Yes  | 2020_10_09_130043_bump_version040007                        | 1     |
| Yes  | 2020_10_15_104504_add_log_max_num_line                      | 1     |
| Yes  | 2020_10_15_161346_sort_image_per_album                      | 1     |
| Yes  | 2020_11_12_183345_config_password_url_param_for_smart_album | 1     |
| Yes  | 2020_11_19_231553_bump_version040008                        | 1     |
| Yes  | 2020_12_12_203153_migrate_admin_user                        | 1     |
| Yes  | 2020_12_12_203831_create_web_authn_tables                   | 1     |
| Yes  | 2020_12_18_162100_bump_version040009                        | 1     |
| Yes  | 2020_12_18_162155_add_nsfw_album                            | 1     |
| Yes  | 2020_12_18_163800_bump_version040010                        | 1     |
| Yes  | 2020_12_24_022307_bump_version040100                        | 1     |
| Yes  | 2020_12_26_153220_nested_set_for_albums                     | 1     |
| Yes  | 2021_01_09_163715_remove_max_min_takestamps                 | 1     |
| Yes  | 2021_01_12_122546_bump_version040200                        | 1     |
| Yes  | 2021_01_18_103729_add_album_cover                           | 1     |
| Yes  | 2021_01_20_113912_bump_version040201                        | 1     |
| Yes  | 2021_01_24_231904_fix-rotation                              | 1     |
| Yes  | 2021_01_27_085903_config_map_display_direction              | 1     |
| Yes  | 2021_01_30_111736_display_takedate                          | 1     |
| Yes  | 2021_02_12_222948_config_upload_processing_limit            | 1     |
| Yes  | 2021_02_13_132245_bump_version040202                        | 1     |
| Yes  | 2021_02_18_232639_config_public_photos_hidden               | 1     |
| Yes  | 2021_03_03_175555_config_remove_image_overlay               | 1     |
| Yes  | 2021_04_17_135924_bump_version040300                        | 1     |
| Yes  | 2064_12_25_0000_generate_installed_log                      | 1     |
+------+-------------------------------------------------------------+-------+
```

I also tried to manually run the migrate command. Again it says there's nothing to migrate. Just like the web UI does.
```
root@lychee-df964cb96-bc2qh:/var/www/html/Lychee# php artisan migrate       

**************************************
*     Application In Production!     *
**************************************

 Do you really wish to run this command? (yes/no) [no]:
 > yes

Nothing to migrate.
```

**Comment by d7415** [comment]
> Ok, I ran the migrate status command

Just double checking - was this on the original or on a 4.3.0 version? Because it looks like it can't see any of the migrations from after that point.

If it's the one from the original post, it would be useful to see the contents of the `database/migrations` directory and the `version.md` file. If it's the 4.3.0 then that's expected.

**Comment by aaronnewsome** [comment]
> > Ok, I ran the migrate status command
> 
> Just double checking - was this on the original or on a 4.3.0 version? Because it looks like it can't see any of the migrations from after that point.
> 
> If it's the one from the original post, it would be useful to see the contents of the `database/migrations` directory and the `version.md` file. If it's the 4.3.0 then that's expected.

The above console outputs are all from 4.3.0. I've since begun trying with 4.3.4 again, with a fresh database restore. I really am going to have to modify the docker image to skip the permissions settings since it takes hours to do the permissions. I was really trying to avoid modifying the docker image, since if I do that, then I'll be posting about issues I'm having with a docker image I created, rather than the official docker image.

Anyway, once I get a new docker image created that can skip the permissions, I should be able to more quickly figure out what the heck is going on since reboots won't take hours. Once this latest boot completes, I'll be able to post the contents of database/migrations and the version.md file.

**Comment by aaronnewsome** [comment]
Ok, here's the update on where I am now. I've spent about 8 hours so far trying to get the instance of Lychee up and running again. I'm no closer to figuring this out. I'm pretty close to just starting over. I really can't figure out what the heck is causing this 503 error when I try to open the WebUI.

I blame myself for using lychee:dev in my config file, since using the dev tag is no way to keep a "known" version running. If the container restarts for any reason, it'll check the dev tag and pull a new image if the dev release is newer. I've been using containers long enough to know that you never do something like use a ":latest" or ":dev" tag for your image spec. It's a sure-fire way to wind up with a broken app, since devs will frequently do things that break apps and tag them with :latest or whatever.

Not sure how I let this one stay configured with :dev but I'm going through all my apps and making sure that every app has an actual version number assigned and not an alias.

So just to be clear here's where I'm at:

- I've returned everything to how it was when the error started occuring, that is ... 
- I've returned the config file to use the **lycheeorg/lychee:dev** image
-  I'm using the same database I've been using for months without any issues (not a restored version of the DB)
- I've moved the image folder out of the way so the image doesn't take hours to boot (this was easier than making my own Docker image to skip the permissions checks)

So, having said all that. Here's the output of some things asked for in this thread.

version key from Database:
```
lychee=# select key, value from configs where key = 'version';
   key   | value  
---------+--------
 version | 040305
```

contents of version.md:
```
root@lychee-8559645645-q954b:/var/www/html/Lychee# cat version.md 
4.3.2
```

contents of database/migrations/:
```
2014_10_12_000000_create_users_table.php
2018_08_03_110935_create_albums_table.php
2018_08_03_110936_create_photos_table.php
2018_08_03_110942_create_configs_table.php
2018_08_03_111324_create_logs_table.php
2018_08_10_134924_move_settings.php
2018_08_15_102039_move_albums.php
2018_08_15_103716_move_photos.php
2018_10_30_135411_sharing.php
2019_02_21_114356_create_pages_table.php
2019_02_21_114408_create_page_contents_table.php
2019_06_21_180451_create_sym_links_table.php
2019_09_28_171753_config_fix.php
2019_09_28_190822_photos_fix.php
2019_10_01_add_livephoto_cols.php
2019_10_02_1400_config_map_display_public.php
2019_10_03_214750_frame_refresh_in_sec.php
2019_10_06_1400_config_map_providers.php
2019_10_06_152017_add_force_32bit_ids.php
2019_10_07_0900_config_map_include_sub_albums.php
2019_10_09_233402_config_map_mod.php
2019_10_11_093442_config_check_update_every.php
2019_12_02_2100_config_exiftool.php
2019_12_15_0700_add_share_button_visible_option.php
2019_12_15_1000_config_check_update_every_cat_fix.php
2019_12_25_0600_config_exiftool_ternary.php
2020_01_018_2300_config_import_via_symlink.php
2020_01_04_1200_config_has_ffmpeg.php
2020_01_26_1200_config_public_sorting.php
2020_01_28_133201_composer_update.php
2020_02_14_0600_location_decoding.php
2020_03_11_124417_increase_length_photo_type.php
2020_03_17_200000_unhide_configs.php
2020_04_19_122905_bump_version.php
2020_04_22_155712_bump_version040002.php
2020_04_29_000250_bump_version040003.php
2020_05_12_114228_rss.php
2020_05_12_161427_bump_version040005.php
2020_05_19_174233_config_prefer_available_xmp_metadata.php
2020_05_26_135052_bump_version040006.php
2020_06_04_104605_config_editor_enabled.php
2020_07_11_104605_config_lossless_optimization.php
2020_07_11_184605_update_licences.php
2020_07_26_085322_config_swipe_tolerance.php
2020_07_29_132731_config_local_takestamp.php
2020_08_21_123622_add_smart_tag_album_cols.php
2020_10_09_130043_bump_version040007.php
2020_10_15_104504_add_log_max_num_line.php
2020_10_15_161346_sort_image_per_album.php
2020_11_12_183345_config_password_url_param_for_smart_album.php
2020_11_19_231553_bump_version040008.php
2020_12_12_203153_migrate_admin_user.php
2020_12_12_203831_create_web_authn_tables.php
2020_12_18_162100_bump_version040009.php
2020_12_18_162155_add_nsfw_album.php
2020_12_18_163800_bump_version040010.php
2020_12_24_022307_bump_version040100.php
2020_12_26_153220_nested_set_for_albums.php
2021_01_09_163715_remove_max_min_takestamps.php
2021_01_12_122546_bump_version040200.php
2021_01_18_103729_add_album_cover.php
2021_01_20_113912_bump_version040201.php
2021_01_24_231904_fix-rotation.php
2021_01_27_085903_config_map_display_direction.php
2021_01_30_111736_display_takedate.php
2021_02_12_222948_config_upload_processing_limit.php
2021_02_13_132245_bump_version040202.php
2021_02_18_232639_config_public_photos_hidden.php
2021_03_03_175555_config_remove_image_overlay.php
2021_04_17_135924_bump_version040300.php
2021_05_02_174300_add_filesize_raw_col.php
2021_05_12_185726_bump_version040301.php
2021_05_13_140700_refactor_size_variants.php
2021_05_16_171615_bump_version040302.php
2021_05_25_160600_post_revert_fixes.php
2021_05_31_201000_convert_filesize_to_bigint.php
2064_12_25_0000_generate_installed_log.php
```

php artisan migrate:status
```
root@lychee-8559645645-q954b:/var/www/html/Lychee# php artisan migrate:status

+------+-------------------------------------------------------------+-------+
| Ran? | Migration                                                   | Batch |
+------+-------------------------------------------------------------+-------+
| Yes  | 2014_10_12_000000_create_users_table                        | 1     |
| Yes  | 2018_08_03_110935_create_albums_table                       | 1     |
| Yes  | 2018_08_03_110936_create_photos_table                       | 1     |
| Yes  | 2018_08_03_110942_create_configs_table                      | 1     |
| Yes  | 2018_08_03_111324_create_logs_table                         | 1     |
| Yes  | 2018_08_10_134924_move_settings                             | 1     |
| Yes  | 2018_08_15_102039_move_albums                               | 1     |
| Yes  | 2018_08_15_103716_move_photos                               | 1     |
| Yes  | 2018_10_30_135411_sharing                                   | 1     |
| Yes  | 2019_02_21_114356_create_pages_table                        | 1     |
| Yes  | 2019_02_21_114408_create_page_contents_table                | 1     |
| Yes  | 2019_06_21_180451_create_sym_links_table                    | 1     |
| Yes  | 2019_09_28_171753_config_fix                                | 1     |
| Yes  | 2019_09_28_190822_photos_fix                                | 1     |
| Yes  | 2019_10_01_add_livephoto_cols                               | 1     |
| Yes  | 2019_10_02_1400_config_map_display_public                   | 1     |
| Yes  | 2019_10_03_214750_frame_refresh_in_sec                      | 1     |
| Yes  | 2019_10_06_1400_config_map_providers                        | 1     |
| Yes  | 2019_10_06_152017_add_force_32bit_ids                       | 1     |
| Yes  | 2019_10_07_0900_config_map_include_sub_albums               | 1     |
| Yes  | 2019_10_09_233402_config_map_mod                            | 1     |
| Yes  | 2019_10_11_093442_config_check_update_every                 | 1     |
| Yes  | 2019_12_02_2100_config_exiftool                             | 1     |
| Yes  | 2019_12_15_0700_add_share_button_visible_option             | 1     |
| Yes  | 2019_12_15_1000_config_check_update_every_cat_fix           | 1     |
| Yes  | 2019_12_25_0600_config_exiftool_ternary                     | 1     |
| Yes  | 2020_01_018_2300_config_import_via_symlink                  | 1     |
| Yes  | 2020_01_04_1200_config_has_ffmpeg                           | 1     |
| Yes  | 2020_01_26_1200_config_public_sorting                       | 1     |
| Yes  | 2020_01_28_133201_composer_update                           | 1     |
| Yes  | 2020_02_14_0600_location_decoding                           | 1     |
| Yes  | 2020_03_11_124417_increase_length_photo_type                | 1     |
| Yes  | 2020_03_17_200000_unhide_configs                            | 1     |
| Yes  | 2020_04_19_122905_bump_version                              | 1     |
| Yes  | 2020_04_22_155712_bump_version040002                        | 1     |
| Yes  | 2020_04_29_000250_bump_version040003                        | 1     |
| Yes  | 2020_05_12_114228_rss                                       | 1     |
| Yes  | 2020_05_12_161427_bump_version040005                        | 1     |
| Yes  | 2020_05_19_174233_config_prefer_available_xmp_metadata      | 1     |
| Yes  | 2020_05_26_135052_bump_version040006                        | 1     |
| Yes  | 2020_06_04_104605_config_editor_enabled                     | 1     |
| Yes  | 2020_07_11_104605_config_lossless_optimization              | 1     |
| Yes  | 2020_07_11_184605_update_licences                           | 1     |
| Yes  | 2020_07_26_085322_config_swipe_tolerance                    | 1     |
| Yes  | 2020_07_29_132731_config_local_takestamp                    | 1     |
| Yes  | 2020_08_21_123622_add_smart_tag_album_cols                  | 1     |
| Yes  | 2020_10_09_130043_bump_version040007                        | 1     |
| Yes  | 2020_10_15_104504_add_log_max_num_line                      | 1     |
| Yes  | 2020_10_15_161346_sort_image_per_album                      | 1     |
| Yes  | 2020_11_12_183345_config_password_url_param_for_smart_album | 1     |
| Yes  | 2020_11_19_231553_bump_version040008                        | 1     |
| Yes  | 2020_12_12_203153_migrate_admin_user                        | 1     |
| Yes  | 2020_12_12_203831_create_web_authn_tables                   | 1     |
| Yes  | 2020_12_18_162100_bump_version040009                        | 1     |
| Yes  | 2020_12_18_162155_add_nsfw_album                            | 1     |
| Yes  | 2020_12_18_163800_bump_version040010                        | 1     |
| Yes  | 2020_12_24_022307_bump_version040100                        | 1     |
| Yes  | 2020_12_26_153220_nested_set_for_albums                     | 1     |
| Yes  | 2021_01_09_163715_remove_max_min_takestamps                 | 1     |
| Yes  | 2021_01_12_122546_bump_version040200                        | 1     |
| Yes  | 2021_01_18_103729_add_album_cover                           | 1     |
| Yes  | 2021_01_20_113912_bump_version040201                        | 1     |
| Yes  | 2021_01_24_231904_fix-rotation                              | 1     |
| Yes  | 2021_01_27_085903_config_map_display_direction              | 1     |
| Yes  | 2021_01_30_111736_display_takedate                          | 1     |
| Yes  | 2021_02_12_222948_config_upload_processing_limit            | 1     |
| Yes  | 2021_02_13_132245_bump_version040202                        | 1     |
| Yes  | 2021_02_18_232639_config_public_photos_hidden               | 1     |
| Yes  | 2021_03_03_175555_config_remove_image_overlay               | 1     |
| Yes  | 2021_04_17_135924_bump_version040300                        | 1     |
| Yes  | 2021_05_02_174300_add_filesize_raw_col                      | 2     |
| Yes  | 2021_05_12_185726_bump_version040301                        | 2     |
| Yes  | 2021_05_13_140700_refactor_size_variants                    | 2     |
| Yes  | 2021_05_16_171615_bump_version040302                        | 2     |
| Yes  | 2021_05_25_160600_post_revert_fixes                         | 2     |
| Yes  | 2021_05_31_201000_convert_filesize_to_bigint                | 2     |
| Yes  | 2064_12_25_0000_generate_installed_log                      | 1     |
+------+-------------------------------------------------------------+-------+
```
attempt to migrate manually
```
root@lychee-8559645645-q954b:/var/www/html/Lychee# php artisan migrate

**************************************
*     Application In Production!     *
**************************************

 Do you really wish to run this command? (yes/no) [no]:
 > yes

Nothing to migrate.
```

and finally, the output of the console when then container is booted:
```
-------------------------------------
  _               _                
 | |   _   _  ___| |__   ___  ___  
 | |  | | | |/ __|  _ \ / _ \/ _ \ 
 | |__| |_| | (__| | | |  __/  __/ 
 |_____\__, |\___|_| |_|\___|\___| 
 | |   |___/ _ __ __ ___   _____| |
 | |   / _' | '__/ _' \ \ / / _ \ |
 | |__| (_| | | | (_| |\ V /  __/ |
 |_____\__,_|_|  \__,_| \_/ \___|_|

-------------------------------------
Lychee Version: 4.3.2 (dev)
Lychee Commit:  3a0798c
https://github.com/LycheeOrg/Lychee/commit/3a0798c62818f87531c4c9505bb6ef292f09227b
-------------------------------------
**** Make sure the /conf and /uploads folders exist ****
**** Create the symbolic link for the /uploads folder ****
**** Create the symbolic link for the /sym folder ****
**** Create the symbolic link to the old Lychee-Laravel folder ****
**** Copy the .env to /conf ****
**** Inject .env values ****
**** Generate the key (to make sure that cookies cannot be decrypted etc) ****

**************************************
*     Application In Production!     *
**************************************

Command Canceled!
**** Migrate the database ****

Nothing to migrate.
**** Check user.css exists and symlink it ****
**** Create user and use PUID/PGID ****
 	User UID :	1026
 	User GID :	100
**** Set Permissions ****
**** Setup complete, starting the server. ****
```

If anyone has ideas, please let me know. Otherwise I'll start fresh and then try and manually put everything back to how it was before the 503 error started all of a sudden. Really not looking forward to that.

**Comment by kamil4** [comment]
The issue is that your database version is in fact *newer* than your Lychee codebase. How that may have happened, I have _no idea_. @d7415 may be able to shed some light...

Your Lychee codebase is from commit 3a0798c, dated June 1. The correct version of the Lychee database corresponding to that codebase is `040302`.

Your database, however, is version `040305`. To get that version, you must have at some point run Lychee codebase dated July 19 or higher. There are, in fact, only four commits on `master` with that database version: 5d5586bbd51fa452a765a2d592ed9811a1cbabd5, 57e104a1d43d932fdd943f88c2a31031ce820064, bc918a394a995a939b6e5651746895c464370a2d, and 65383e495465cc93bfadad7a4ffa4d51c67503a4 (the current HEAD).

To overcome the issues you are seeing, you need to either find a docker image with a Lychee codebase corresponding to one of the above commits, or keep the codebase you are using, but restore from your backup a database with version `040302` or older.

You've got two viable paths of solving this. You should _not_ need to start from scratch. Persevere! :smile:

**Comment by aaronnewsome** [comment]
Fixed by updating the docker image to:

```
Lychee Version: 4.3.2 (dev)
Lychee Commit:  3a0798c
lycheeorg/lychee:testing-1121268399
```

I'm no longer going to use the :dev tag for the docker image also. Lastly, I've tagged the docker image and pushed it to my own docker repository so there's no chance that it'll change on me again.

That's my only explanation to what happened here. It must have been that somehow a newer image was pushed to the dev tag and then rolled back. Otherwise, how could my database version have gotten AHEAD of the version of lychee on the :dev tag?

My Docker config files are under version control too. I checked and the docker config had only used the :dev tag for months now.

A real head scratcher but now solved. Leaving the issue open in case someone wants to post a last comment before closing the issue.

**Comment by d7415** [comment]
The `:dev` on Docker Hub won't go backwards - it builds every day from `master`. It looks the database only got ahead while you were trying other things, and I guess picked up a new `:dev` image. When you went back to the 4.3.2 one it was already migrated ahead. That still doesn't explain the original issue, but at some point the migration worked, and when you rolled back to the initial image the 4.3.2 migration worked too.

As I said, the original issue is still an unknown, but at some point the migration worked, so I think we can close this for now.
