### ISSUE TITLE
Moving photos from an admin album to an user one causes ownership errors

### ISSUE THREAD

**Issue by ynsta** [LycheeOrg/Lychee#1187]
### Steps to reproduce the issue

1. Create an album test as admin user
2. Upload a photo into test
3. Relog as user
4. Create an album test2 as an user
5. Relog as admin
6. Move photo from test to test2 (user album)
7. Relog as user
8. Go to into album test2
9. Try to set photo as favorite (star)
10. An error is shown and logs contains :

```
2022-01-04 11:40:08 -- error   -- App\Http\Middleware\UploadCheck::photo_check -- 143 -- Photos not found or ownership mismatch!
```

### Output of the diagnostics

```
    Diagnostics
    -----------
    Warning: Dropbox import not working. dropbox_key is empty.
    Info: Latest version of PHP is 8

    System Information
    ------------------
    Lychee Version (git):            No git data found.
    DB Version:                      4.3.6
    
    composer install:                --no-dev
    APP_ENV:                         production
    APP_DEBUG:                       false
    
    System:                          Linux
    PHP Version:                     7.4
    Max uploaded file size:          2048M
    Max post size:                   2048M
    MySQL Version:                   10.6.5-MariaDB-1:10.6.5+maria~focal
    
    Imagick:                         1
    Imagick Active:                  1
    Imagick Version:                 1691
    GD Version:                      2.3.0

    Config Information
    ------------------
    version:                         040306
    check_for_updates:               0
    sorting_Photos_col:              taken_at
    sorting_Photos_order:            ASC
    sorting_Albums_col:              max_taken_at
    sorting_Albums_order:            ASC
    imagick:                         1
    skip_duplicates:                 0
    small_max_width:                 0
    small_max_height:                360
    medium_max_width:                1920
    medium_max_height:               1080
    lang:                            fr
    layout:                          1
    image_overlay_type:              date
    default_license:                 reserved
    compression_quality:             90
    full_photo:                      1
    delete_imported:                 0
    Mod_Frame:                       1
    Mod_Frame_refresh:               30
    thumb_2x:                        1
    small_2x:                        1
    medium_2x:                       1
    landing_page_enable:             0
    landing_owner:                   REMOVED
    landing_title:                   REMOVED
    landing_subtitle:                Photography
    landing_facebook:                
    landing_flickr:                  
    landing_twitter:                 REMOVED
    landing_instagram:               
    landing_youtube:                 
    landing_background:              dist/cat.jpg
    site_title:                      Photos
    site_copyright_enable:           1
    site_copyright_begin:            2021
    site_copyright_end:              2022
    additional_footer_text:          
    display_social_in_gallery:       0
    public_search:                   0
    SL_enable:                       0
    SL_for_admin:                    0
    public_recent:                   0
    recent_age:                      1
    public_starred:                  0
    downloadable:                    0
    photos_wraparound:               1
    map_display:                     0
    zip64:                           1
    map_display_public:              0
    map_provider:                    Wikimedia
    force_32bit_ids:                 0
    map_include_subalbums:           0
    update_check_every_days:         3
    has_exiftool:                    1
    share_button_visible:            0
    import_via_symlink:              0
    has_ffmpeg:                      1
    location_decoding:               0
    location_decoding_timeout:       30
    location_show:                   1
    location_show_public:            0
    rss_enable:                      0
    rss_recent_days:                 7
    rss_max_items:                   100
    prefer_available_xmp_metadata:   0
    editor_enabled:                  1
    lossless_optimization:           0
    swipe_tolerance_x:               150
    swipe_tolerance_y:               250
    local_takestamp_video_formats:   .avi|.mov
    log_max_num_line:                1000
    unlock_password_photos_with_url_param: 0
    nsfw_visible:                    1
    nsfw_blur:                       0
    nsfw_warning:                    0
    nsfw_warning_admin:              0
    map_display_direction:           1
    album_subtitle_type:             oldstyle
    upload_processing_limit:         4
    public_photos_hidden:            1
    new_photos_notification:         1
```

### Browser and system

Mozilla/5.0 (X11; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0

**Comment by ynsta** [comment]
I fixed my issue by changing the owner_id in the photos table to set the user as owner.

**Comment by kamil4** [comment]
Thanks for the report! This looks like a regression as I'm pretty sure that it used to work correctly in the past... Either way, we are in the middle of a major refactoring of our code (#1055) yet I can still reproduce it there. We will fix it on that branch which will eventually probably become Lychee 5.0 but unfortunately we are unlikely to make any more incremental 4.x releases at this point.
