### ISSUE TITLE
[Enhancement] Metadata Exif description field

### ISSUE THREAD

**Issue by crusty49** [LycheeOrg/Lychee#1548]
*Explain in a few words which functionality or improvements you would like to see in Lychee.*
I'm just trialling Lychee at the moment. I notice that when uploading images the "description" field doesn't get imported even though it exists in the original file. Neither does it seem to get exported when downloading the file.

Is this intentional, or a bug? Any chance of a fix?

Or am I doing something wrong?

**Comment by ildyria** [comment]
> Neither does it seem to get exported when downloading the file.

Lychee does not modify the uploaded files (which thus count as including adding metadata).
Any description added stays in Lychee.

As for the import, Can you double check where it exists in the exif data. This should help us see where to find it for https://github.com/LycheeOrg/php-exif

**Comment by kamil4** [comment]
Yes, reading the description from the image file is definitely supposed to work. We've had a bug in the code that handles it, but it was fixed nearly a year ago: #1117. If you are using an old version of Lychee though (such as 4.4.0), you would likely be affected.

If you are using a more recent version, please provide us with Lychee diagnostics output as well as a sample image file that exhibits the problem and we'll see what the issue might be...

**Comment by crusty49** [comment]
Thanks for the fast response. I'm using 4.6.0 Attached diagnostics dump.
I notice the warning in the dump about time zone not set. Can't see anywhere to specify time zone in Lychee.
I'm using Exif Pilot to add exif to old B/W scans.
Attached a sample pic.
Hope I have done this right.
Thanks, Bruce

![exif](https://user-images.githubusercontent.com/114981215/193946541-ed922362-b15f-4123-82b0-38d55dd7002e.jpg)
![1945c1](https://user-images.githubusercontent.com/114981215/193946552-f99e09d6-6ef0-4c3d-a719-28274e0d145d.png)

Link to Google drive copy of image https://drive.google.com/file/d/1vMwxxD6SKPiI50WPj5Xq68Q8SxTWlBt3/view?usp=sharing

**Comment by crusty49** [comment]
Whoops... forgot the diagnostic.

[diagnostics.txt](https://github.com/LycheeOrg/Lychee/files/9711412/diagnostics.txt)

**Comment by kamil4** [comment]
This is a bug in php-exif, our metadata extractor.

Our preferred metadata extracting backend is Exiftool, and your image works fine with it. However, because according to your diagnostics you have `exec` disabled on the server, you can't use Exiftool.

The metadata extractor then falls back to the Imagick backend, which happens to have a small typo. Until we get it fixed in a future release (probably 4.6.2), you can fix it yourself by editing the file `Lychee/vendor/lychee-org/php-exif/lib/PHPExif/Mapper/ImageMagick.php`.  Line 36 looks as follows:
```
    const DESCRIPTION              = 'exif:ImageDescription ';
```
Can you see a space between `ImageDescription` and `'`? It needs to be removed, so that the line looks like this:
```
    const DESCRIPTION              = 'exif:ImageDescription';
```
This will fix it for you.

Regarding the time zone, you can set it by editing the file `Lychee/.env`.

**Comment by kamil4** [comment]
Are you OK with us adding your image to our testsuite?

**Comment by crusty49** [comment]
> 

Yes file to use the image

**Comment by crusty49** [comment]
Thanks for your fast response. I applied the fix as you suggested, but got an error when uploading.
I reversed the fix, same problem. Removed the Lychee install (inc. folder files and database), reinstalled and still fails.
Installed to a different folder , and even a different domain but still no good.
Tried different images for the upload.
It doesn't seem to generate a server error, cpanel error log doesn't show a problem.
Unfortunately I didn't try an upload before the fix.
Maybe I should just wait for 4.6.2. I'm not sure it is your problem. Will have to do some more work on it.
Thanks, Bruce
![upload failed](https://user-images.githubusercontent.com/114981215/194220096-ed7f3862-7e18-4519-aaec-19c4e7b9ad5d.jpg)

**Comment by crusty49** [comment]
Hi there, just an update. Lychee install came good, not sure what the problem was.
Anyhow, have applied the fix above to exif:ImageDescription, but description is not showing, and in fact not being written to the database.
Cheers, Bruce

**Comment by kamil4** [comment]
Strange; it works here.

I'll try to get the fix included in the next release (4.6.2, probably) so hopefully that will fix it for you without any additional effort on your side!

**Comment by crusty49** [comment]
Thanks very much. Will keep an eye out for the new version.
